### PR TITLE
Refuse penalty depends on time

### PR DESCRIPTION
**Pull request by g4s8**
#1926 - penalize for refuse by new policy rules: https://www.zerocracy.com/policy.html#6

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#2167](https://github.com/zerocracy/farm/issues/2167) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/2167#issuecomment-541155286))

@g4s8 The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#2167](https://github.com/zerocracy/farm/issues/2167), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#2167](https://github.com/zerocracy/farm/issues/2167) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/535dc8a6-dcc0-4274-830f-7f2978599276); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 15 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@35e4a901-03b4-4c56-aeaf-061760a7a54d, thread: pool-7-thread-1
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zerocracy/farm#2167] declared for identity constraint of element "speed".
```

[0.49.18](https://github.com/zerocracy/farm): CID: [66ee7769-f2ac-4bfe-bc80-7daf991277f9](https://www.0crat.com/footprint/C3NDPUA8L/66ee7769-f2ac-4bfe-bc80-7daf991277f9), Type: "Order was finished"

**Comment by 0crat** [comment]
The job [#2167](https://github.com/zerocracy/farm/issues/2167) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Pull request merged**
