### PR TITLE
Set boost for a job

### PR DESCRIPTION
**Pull request by g4s8**
#184 - set boost for a job

### CODE REVIEW

**Comment by fabriciofx** [comment]
@g4s8 Can you check why this merge (EstimatesTest) failed?

**Comment by g4s8** [comment]
@fabriciofx actually EstimatesTest completed successfully:
> Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.298 sec

 this process was killed by Rultor after 2 hours of execution. It's because of this bug https://github.com/zerocracy/farm/issues/416

**Comment by g4s8** [comment]
Moved here #459 (missed fork)

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), total is [+285](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8160](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#395](https://github.com/zerocracy/farm/issues/395) is now out of scope

**Pull request closed without merging**
