### PR TITLE
#768 Implement HeapDump.save

### PR DESCRIPTION
**Pull request by carlosmiranda**
#768: Implement `HeapDump.save` functionality. Added `HeapDumpTest` and added related tests there.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1103](https://github.com/zerocracy/farm/issues/1103) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@carlosmiranda looks ok. Personally, I don't like the overall solution (it's not your fault, that's how it started, with class HeapDump)... I would have made something like:

```java
final class HeapDump implements Bucket {
    private Path pathToDump;
    private Bucket toSave;
    ...
}
```

This would have avoided that much procedural code inside ``save``, I believe. 

Also, it seems to me you worked more than 30min here -- if that's the case, try to use PDD next time, since it's not ok for the project to receive more work than it pays for.

**Comment by amihaiemil** [comment]
@g4s8 looks ok to me

**Comment by g4s8** [comment]
@rultor merge

**Comment by carlosmiranda** [comment]
@amihaiemil worked on it on-and-off over multiple days ("life" kept me constantly sidetracked), so I probably did a bit more than 30 min. :)

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by amihaiemil** [comment]
@ypshenychka I confirm. Well, I did ask the performer to break down the work in more puzzles. Working more than 30min is not ok for the project's image, it is not ethical from the project's side :)

**Comment by ypshenychka** [comment]
@amihaiemil I agree that this is something that ticket performer should've thought of prior implementation. But I can't call this "problem in the code" that you found as a code reviewer. It's more like advice for the next time. Agree?

**Comment by amihaiemil** [comment]
@ypshenychka yes, of course :D

**Comment by ypshenychka** [comment]
@amihaiemil Thanks!

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
