### PR TITLE
#1691 Add release details in ARC payment as "job" param

### PR DESCRIPTION
**Pull request by carlosmiranda**
#1691: Release bonus payment now includes tag and repo details instead of merely "none" as the job param.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1772](https://github.com/zerocracy/farm/issues/1772) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@carlosmiranda please see error in tests:
```
oneBundleWorksFine[com/zerocracy/bundles/pays_architect_for_release](com.zerocracy.BundlesTest)  Time elapsed: 7.568 sec  <<< ERROR!
java.lang.IllegalStateException: java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'tag 0.1 in repo test/test' is not facet-valid with respect to pattern 'none|gh:[A-Z0-9a-z.\-#/]{3,}' for type 'jobID'.;-1:-1: cvc-type.3.1.3: The value 'tag 0.1 in repo test/test' of element 'job' is not valid.
```

**Comment by g4s8** [comment]
@carlosmiranda yes, if it makes each debt unique

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1772` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1772](https://github.com/zerocracy/farm/issues/1772) is now out of scope

**Pull request merged**
