### PR TITLE
Fixed yoti deps

### PR DESCRIPTION
**Pull request by g4s8**
#1977 - updated yoti library to 2.0, fixed fasterxml.jackson dependency

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1998](https://github.com/zerocracy/farm/issues/1998) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1998` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1998](https://github.com/zerocracy/farm/issues/1998) is now out of scope

**Pull request merged**
