### PR TITLE
Cleanup comments

### PR DESCRIPTION
**Pull request by g4s8**
#376 - cleanup comments
(#379 PR)

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#455](https://github.com/zerocracy/farm/issues/455) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#455](https://github.com/zerocracy/farm/issues/455) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by g4s8** [comment]
@fabriciofx this PR was already reviewed by @yegor256 here #379, but my local fork was missed by Github when "farm" project becomes public, could you please take a look?

**Comment by fabriciofx** [comment]
@g4s8 I received this warning:
```
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 699, column 19
```
Could you fix it?

**Comment by g4s8** [comment]
@fabriciofx done, please see 243abb4022fdb791acb6b922a2ba7c186440ee02

**Comment by g4s8** [comment]
@fabriciofx please, see this PR

**Comment by 0crat** [comment]
The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#455](https://github.com/zerocracy/farm/issues/455), please stop working

**Comment by 0crat** [comment]
This pull request [#455](https://github.com/zerocracy/farm/issues/455) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by carlosmiranda** [comment]
@yegor256 should be assigned to @fabriciofx I think

**Comment by yegor256** [comment]
@0crat assign @fabriciofx

**Comment by 0crat** [comment]
> @0crat assign @fabriciofx  ([here](https://github.com/zerocracy/farm/issues/455#issuecomment-363097340))

@yegor256 This pull request [#455](https://github.com/zerocracy/farm/issues/455) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9285](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 this PR is here about 2 weeks and you have already reviewed it in #379, maybe we can merge it?

**Comment by yegor256** [comment]
@g4s8 try to ping code reviewer first, please

**Comment by g4s8** [comment]
@fabriciofx ping

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/455#issuecomment-364359589))

@g4s8 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#455](https://github.com/zerocracy/farm/issues/455) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 16days
  * The role is `REV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [4days](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) will get 25% of their hourly rate for this job
  * Some equity will be [vested](http://datum.zerocracy.com/pages/policy.html#37) on completion
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): User was resigned from the ticket
    * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda): User was resigned from the ticket

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@fabriciofx ping

**Comment by 0crat** [comment]
The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#455](https://github.com/zerocracy/farm/issues/455), please stop working

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/455#issuecomment-366165191))

@g4s8 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#455](https://github.com/zerocracy/farm/issues/455) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 23days
  * The role is `REV`
  * The job is not assigned to anyone
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): User was resigned from the ticket
    * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda): User was resigned from the ticket
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23455%27%7D) (restricted area)

**Comment by g4s8** [comment]
@yegor256 this PR is not assigned to anyone, could you please take a look?

**Comment by yegor256** [comment]
@rultor merge

**Comment by g4s8** [comment]
@yegor256 looks like port `44744` generated for jcaby-dynamodb-maven-plugin is used by Rultor,
maybe I need to restrict it with `reserve-network-port` configuration?
```xml
<configuration>
  <minPortNumber></minPortNumber>
  <maxPortNumber></maxPortNumber>
</configuration>
```
But I didn't find what port can be used in [Rultor documentation](http://doc.rultor.com/reference.html), do you know where I can get it?

**Comment by yegor256** [comment]
@g4s8 it's something else... Rultor is not using any ports. The build starts in its own Docker container, where all ports are available. It seems that something else is wrong. Let's try to merge again.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#455](https://github.com/zerocracy/farm/issues/455) is now out of scope

**Pull request merged**
