### PR TITLE
#640 Switched CcXor to CcAes

### PR DESCRIPTION
**Pull request by carlosmiranda**
#640: Changed `CcXor` to `CcAes`. Also switched property name from `xor.key` to `aes.key`.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#647](https://github.com/zerocracy/farm/issues/647) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@carlosmiranda I don't think it's that easy, see the failures above

**Comment by 0crat** [comment]
This pull request [#647](https://github.com/zerocracy/farm/issues/647) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/570637241). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by carlosmiranda** [comment]
@yegor256 Something's wrong with `CcAes`, or I'm using it wrong. `CcSecureTest` passes fine. However, when we are now using it within `TkApp` the decode operation fails. This results in `ANONYMOUS` being returned and pages not being rendered:

```
org.takes.facets.auth.codecs.DecodingException: checksum 43 failure, while 0 expected
	at org.takes.facets.auth.codecs.CcSalted.unsalt(CcSalted.java:117)
	at org.takes.facets.auth.codecs.CcSalted.decode(CcSalted.java:70)
	at org.takes.facets.auth.codecs.CcAes.decode(CcAes.java:102)
	at org.takes.facets.auth.codecs.CcHex.decode(CcHex.java:117)
	at org.takes.facets.auth.codecs.CcSafe.decode(CcSafe.java:64)
	at com.zerocracy.tk.CcSecure.decode(CcSecure.java:72)
	at org.takes.facets.auth.PsCookie.enter(PsCookie.java:105)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at com.zerocracy.tk.TkSslOnly.act(TkSslOnly.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at com.zerocracy.tk.TkGutsTest.rendersXml(TkGutsTest.java:46)
``

**Comment by carlosmiranda** [comment]
@yegor256 @g4s8 ping...

**Comment by yegor256** [comment]
@rultor merge

**Comment by carlosmiranda** [comment]
@yegor256 merged with master, let's try again

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/finish_order.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
org.cactoos.scalar.Or[154] java.lang.NullPointerException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@yegor256 could you please remove this job from WBS?

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/647#issuecomment-370429269))

@yegor256 @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#647](https://github.com/zerocracy/farm/issues/647), since the job is not in scope anymore

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/647#issuecomment-370429269))

@yegor256 The job [#647](https://github.com/zerocracy/farm/issues/647) is now out of scope

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/647#issuecomment-370429269))

@yegor256 Job [#647](https://github.com/zerocracy/farm/issues/647) was not in scope

**Pull request merged**
