### PR TITLE
#403 Add "in" label to Github tasks in scope

### PR DESCRIPTION
**Pull request by carlosmiranda**
#403 
* Add "in" label to Github tasks in scope
* Added Bundles Test case
* Added puzzle for removing label on tasks out of scope

### CODE REVIEW

**Comment by carlosmiranda** [comment]
@fabriciofx what do you think?

**Comment by fabriciofx** [comment]
@yegor256 @carlosmiranda This PR seems fine to me. I accept it.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), total is [+345](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8330](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#445](https://github.com/zerocracy/farm/issues/445) is now out of scope

**Pull request merged**
