### PR TITLE
Fix travis build so we will see qulice errors

### PR DESCRIPTION
**Pull request by krzyk**
When using `--quiet` no INFO messages from qulice are shown, I removed it.

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by krzyk** [comment]
@g4s8 ping

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1253` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Pull request merged**
