### PR TITLE
App shutdown

### PR DESCRIPTION
**Pull request by g4s8**
#476 - added app shutdown interface, using it in `TkShutdown`, `DefaultFlush` and `Main`, added stub class with `todo` to implement.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#639](https://github.com/zerocracy/farm/issues/639) is now in scope, role is `REV`

**Comment by carlosmiranda** [comment]
@yegor256 good to merge

**Comment by yegor256** [comment]
@g4s8 I don't think it's a wrong design, but I think we can do better. With this design each class that is using any background threads will have to know about `ExtShutdown` and will have to use it. Once in a while we will forget about that and will create threads that will not be under control. I'm suggesting to do something more generic.

How about we create our own implementation of `ThreadFactory`, which will return threads that are aware of our shutdown mechanism. Everybody, every single `ExecutorService` will use that factory. And when it's time to shutdown, we will just inform the factory about it and it will gracefully shut down all threads. WDYT?

**Comment by g4s8** [comment]
@yegor256 you are right - `ThreadFactory` would be better, please look new commits

**Comment by yegor256** [comment]
@g4s8 looks like over-design to me. First, why do we need `ExtShutdown` and `ShutdownThreads`? Can't we just have `ShutdownThreads`? Second, why do we need to create a custom `Runnable` just to throw an exception? Can't we throw the exception right in `newThread()`?

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@yegor256 first - I agree, added `todo` for refactoring. Second - this `Runnable` also acquiring and releasing shutdown locks , not just catching exceptions.

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@g4s8 I feel that we are not solving any problems with this... Most of `ExecutorService`s won't ask for new threads. They will use the existing ones. And we won't really shutdown anything. And the design looks rather verbose and complex. I really suspect that if we merge this we will have to delete it very soon. We need something smaller and more elegant. I don't know exactly what, but this looks wrong to me. Maybe we need something very simple as a prototype first. Instead of implementing, we need an idea first. Maybe an analysis of where exactly the threads are used and what is important to shutdown.

**Comment by 0crat** [comment]
The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#639](https://github.com/zerocracy/farm/issues/639), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by g4s8** [comment]
@yegor256 so what do you think about implementing `ExecutorService` instead of `ThreadFactory`? It can decorate another `ExecutorService` and wrap `Runnable`s with shutdown signals check and skip execution if shutdown was requested:
```java
class ShutdownExec implements ExecutorService {
  private final ExecutorService exec;
  @Override
  public void submit(final Runnable run) {
    this.exec.submit(new CheckShutdownRunnable(run));
  }

  class CheckShutdownRunnable implements Runnable {
    private final Runnable origin;
    public void run() {
      if (!shutdown()) {
        this.origin.run();
      }
    }
  }
```

**Comment by yegor256** [comment]
@g4s8 what are the sensitive places? Let's start with this question. I still think that we are moving the wrong direction...

**Comment by g4s8** [comment]
@yegor256 I think the sensitive places are all radars, claim claims processing and pings. So I'm suggesting to stop accepting new claims (do not start new stakeholders for them, but add to `claims.xml`, we need to save claims in xml because running stakeholders can post new claims via `claim.reply` or `claim.copy`) and wait for all running stakeholders to complete.  Respond with some service-message for all chat-radars, e.g. 'server is restarting, please try again later'  and send http error code in Github radar, because re-http can redeliver it after restart. Also we should stop pings on shutdown.

**Comment by g4s8** [comment]
@yegor256 could you please answer here https://github.com/zerocracy/farm/pull/639#issuecomment-373680453

**Comment by yegor256** [comment]
@g4s8 it seems that if `SyncFarm` will stop giving permissions/locks to new projects and will wait until all locks are "free" -- the problem will be solved, right? We can just introduce a new method `freeze()` at `SyncFarm`, which will wait for that situation. Then, at the shutdown moment we will call `freeze()` and wait. See the strategy?

**Comment by g4s8** [comment]
@yegor256 please look at this issue: https://github.com/zerocracy/farm/issues/855 - it's not clear how does `Guts` work in `SyncFarm`

**Comment by g4s8** [comment]
@yegor256 I think it can work, please look at new commit e12f779

**Comment by g4s8** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@g4s8 now it's just a rename of a puzzle? It's not enough for a PR. I understand that you've spent time here, but it's not a fault of the project. In the future, try to move slower when tasks are complex and ambiguous. Make smaller changes, to avoid spending too much time upfront.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by g4s8** [comment]
@yegor256 please see 8e9dc6d

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#639](https://github.com/zerocracy/farm/issues/639) is now out of scope

**Pull request merged**
