### PR TITLE
#497 Agenda.removeAll() on destroy

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #497

Added and tested method ``Agenda.removeAll(...)``. The alternative was to call ``Agenda.item()`` and run the xpath query inside ``destroy.groovy``, but I think it's better to keep XML classes out of the groovy scripts, let them be encapsulated.

### CODE REVIEW

**Comment by amihaiemil** [comment]
Closing for now, waiting for master to be fixed, so build can pass.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/start_order.groovy
sun.reflect.GeneratedMethodAccessor121[-1] java.lang.reflect.InvocationTargetException: null
org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation[582] groovy.lang.GroovyRuntimeException: Cannot compare com.jcabi.xml.ListWrapper with value '[gh:zerocracy/farm#65, gh:zerocracy/farm#29, gh:zerocracy/farm#89, gh:zerocracy/farm#95, gh:zerocracy/farm#194, gh:zerocracy/farm#199, gh:zerocracy/farm#208, gh:zerocracy/farm#213, gh:zerocracy/farm#207, gh:zerocracy/datum#309, gh:zerocracy/farm#706, gh:zerocracy/farm#720, gh:zerocracy/farm#744, gh:zerocracy/datum#321, gh:zerocracy/farm#704, gh:zerocracy/farm#752, gh:zerocracy/datum#324, gh:zerocracy/farm#771, gh:zerocracy/farm#782, gh:zerocracy/farm#784, gh:zerocracy/farm#785, gh:zerocracy/farm#786, gh:zerocracy/farm#790]' and java.lang.Integer with value '32'
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/start_order.groovy
sun.reflect.GeneratedMethodAccessor121[-1] java.lang.reflect.InvocationTargetException: null
org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation[582] groovy.lang.GroovyRuntimeException: Cannot compare com.jcabi.xml.ListWrapper with value '[gh:zerocracy/farm#65, gh:zerocracy/farm#29, gh:zerocracy/farm#89, gh:zerocracy/farm#95, gh:zerocracy/farm#194, gh:zerocracy/farm#199, gh:zerocracy/farm#208, gh:zerocracy/farm#213, gh:zerocracy/farm#207, gh:zerocracy/datum#309, gh:zerocracy/farm#706, gh:zerocracy/farm#720, gh:zerocracy/farm#744, gh:zerocracy/datum#321, gh:zerocracy/farm#704, gh:zerocracy/farm#752, gh:zerocracy/datum#324, gh:zerocracy/farm#771, gh:zerocracy/farm#782, gh:zerocracy/farm#784, gh:zerocracy/farm#785, gh:zerocracy/farm#786, gh:zerocracy/farm#790]' and java.lang.Integer with value '32'
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/start_order.groovy
sun.reflect.GeneratedMethodAccessor121[-1] java.lang.reflect.InvocationTargetException: null
org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation[582] groovy.lang.GroovyRuntimeException: Cannot compare com.jcabi.xml.ListWrapper with value '[gh:zerocracy/farm#65, gh:zerocracy/farm#29, gh:zerocracy/farm#89, gh:zerocracy/farm#95, gh:zerocracy/farm#194, gh:zerocracy/farm#199, gh:zerocracy/farm#208, gh:zerocracy/farm#213, gh:zerocracy/farm#207, gh:zerocracy/datum#309, gh:zerocracy/farm#706, gh:zerocracy/farm#720, gh:zerocracy/farm#744, gh:zerocracy/datum#321, gh:zerocracy/farm#704, gh:zerocracy/farm#752, gh:zerocracy/datum#324, gh:zerocracy/farm#771, gh:zerocracy/farm#782, gh:zerocracy/farm#784, gh:zerocracy/farm#785, gh:zerocracy/farm#786, gh:zerocracy/farm#790]' and java.lang.Integer with value '32'
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/793#issuecomment-401085401))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#793](https://github.com/zerocracy/farm/issues/793) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 3mon
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will receive 15 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23793%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request closed without merging**
