### PR TITLE
Claim take

### PR DESCRIPTION
**Pull request by g4s8**
#380 - take to render a claim from footprint

### CODE REVIEW

**Comment by g4s8** [comment]
Moved to #461 (missed fork)

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), total is [+300](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8205](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job [#441](https://github.com/zerocracy/farm/issues/441) was not in scope

**Comment by 0crat** [comment]
The job [#441](https://github.com/zerocracy/farm/issues/441) is now out of scope

**Pull request closed without merging**
