### PR TITLE
Claim take

### PR DESCRIPTION
**Pull request by g4s8**
#380 - take to render a claim from footprint
(from #441)

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#461](https://github.com/zerocracy/farm/issues/461) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#461](https://github.com/zerocracy/farm/issues/461) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/461#issuecomment-360787684))

@yegor256 This pull request [#461](https://github.com/zerocracy/farm/issues/461) is assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8445](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/461#issuecomment-360788061))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#461](https://github.com/zerocracy/farm/issues/461) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 1days
  * The role is `REV`
  * The job is assigned to @yegor256[/z](https://www.0crat.com/u/yegor256) for [2min](http://datum.zerocracy.com/pages/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://datum.zerocracy.com/pages/policy.html#2) job
  * Some equity will be [vested](http://datum.zerocracy.com/pages/policy.html#37) on completion
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 15 minutes
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): User was resigned from the ticket

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8460](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8475](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#461](https://github.com/zerocracy/farm/issues/461) is now out of scope

**Pull request merged**
