### PR TITLE
Pay arc for merged prs

### PR DESCRIPTION
**Pull request by g4s8**
#1897 - pay ARC 10min only for merged pull requests

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1987](https://github.com/zerocracy/farm/issues/1987) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1987` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1987](https://github.com/zerocracy/farm/issues/1987) is now out of scope

**Pull request merged**
