### PR TITLE
modify the list of sandbox projects

### PR DESCRIPTION
**Pull request by yegor256**
Let's update them a bit. I'm removing PDD and adding Zold-Ruby.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@yegor256 maybe we need some mechanism to mark project as "sandbox" in Slack channel (e.g. PMO user may say `@0crat sanbox on|off`)?

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1443` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Pull request merged**
