### PR TITLE
StkSafe refactoring

### PR DESCRIPTION
**Pull request by g4s8**
#273 - StkSafe & ReSafe (github, slack, telegram) refactoring

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#466](https://github.com/zerocracy/farm/issues/466) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#466](https://github.com/zerocracy/farm/issues/466) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by 0crat** [comment]
The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#466](https://github.com/zerocracy/farm/issues/466), please stop working

**Comment by 0crat** [comment]
This pull request [#466](https://github.com/zerocracy/farm/issues/466) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@g4s8 need to fix merge conflicts

**Comment by 0crat** [comment]
The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#466](https://github.com/zerocracy/farm/issues/466), please stop working

**Comment by g4s8** [comment]
I'm closing because of https://github.com/zerocracy/farm/issues/273#issuecomment-364933601

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#466` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#466](https://github.com/zerocracy/farm/issues/466) is now out of scope

**Pull request closed without merging**
