### PR TITLE
GitHub close keyword abuse problem

### PR DESCRIPTION
**Pull request by g4s8**
#539 - close job test and `@todo` with next steps

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#567](https://github.com/zerocracy/farm/issues/567) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#567](https://github.com/zerocracy/farm/issues/567) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/461403087). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by carlosmiranda** [comment]
@yegor256 everything looks good here

**Comment by yegor256** [comment]
@rultor merge

**Comment by g4s8** [comment]
@yegor256 `close_job` script was changed a bit in master, so I fixed test here 791772c0d17f2e8a373e6866e5071905f06dd48f
please, restart merge if you accept these changes

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), total is [+1395](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10124](https://www.0crat.com/u/yegor256)

**Pull request merged**
