### PR TITLE
Performance issues (locking)

### PR DESCRIPTION
**Pull request by g4s8**
#1706 fix
 - added read-write locks
 - correct usage of `InterruptedException`
 - removed `Terminator` class, using another way to cancel tasks

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1875](https://github.com/zerocracy/farm/issues/1875) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1875` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1875](https://github.com/zerocracy/farm/issues/1875) is now out of scope

**Pull request merged**
