### PR TITLE
Pay to any Zerocracy user for bug reporting

### PR DESCRIPTION
**Pull request by g4s8**
zerocracy/datum#248 - reproduced and fixed behavior in https://github.com/zerocracy/datum/issues/248 bug

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#641](https://github.com/zerocracy/farm/issues/641) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#641](https://github.com/zerocracy/farm/issues/641) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/560557095). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by carlosmiranda** [comment]
@yegor256 @g4s8 one clarification here regarding the original ticket. My understanding of https://github.com/zerocracy/datum/issues/248 is that we should award points to contributors who may not be members of the project but are part of the gang, should we _pay_ them automatically as well?

**Comment by g4s8** [comment]
@carlosmiranda yes: https://github.com/zerocracy/datum/issues/248#issuecomment-361379244

**Comment by carlosmiranda** [comment]
@yegor256 looks good to merge

**Comment by yegor256** [comment]
@g4s8 the concern of @carlosmiranda was valid. We should not pay cash for those bugs, but only give points. With the changes you introduce we will also pay them cash. To avoid that you can add `cash` param to the claim with the value `0`. That will tell `make_payment.groovy` that no money should be actually transferred to the user. But points will be awarded.

**Comment by g4s8** [comment]
@yegor256 I think it is already so, because that person will not have rate in the project:
```groovy
// make_payemnt.groovy
  if (claim.hasParam('cash')) {
    price = new Cash.S(claim.param('cash'))
  } else {
    Cash rate = Cash.ZERO
    Rates rates = new Rates(project).bootstrap()
    if (rates.exists(login)) {
      rate = rates.rate(login)
    }
    price = rate.mul(minutes) / 60
  }
```
so `price` will always be `Cash.ZERO`

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), total is [+1620](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#641](https://github.com/zerocracy/farm/issues/641) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10899](https://www.0crat.com/u/yegor256)

**Pull request merged**
