### PR TITLE
Typo and grammar fixes

### PR DESCRIPTION
**Pull request by vassilevsky**

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#2065](https://github.com/zerocracy/farm/issues/2065) is now in scope, role is `REV`

**Comment by sbzDev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/2065#issuecomment-499127275))

@sbzDev This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#2065](https://github.com/zerocracy/farm/issues/2065) is [in scope](http://www.zerocracy.com/policy.html#14) for 4days
  * The role is `REV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @vassilevsky[/z](https://www.0crat.com/u/vassilevsky): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%232065%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@vassilevsky thanks!

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2065` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#2065](https://github.com/zerocracy/farm/issues/2065) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
