### PR TITLE
#1123 Re-enable Jobs and Agenda display in Team page

### PR DESCRIPTION
**Pull request by carlosmiranda**
#1123 After the fixes in #841 and #1267, speed and agenda data for users are now stored in `people.xml` ("jobs" element for agenda) instead of being computed on each page load. This fix will display those elements on the Teams page.

### CODE REVIEW

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@carlosmiranda  I think we need to test this page somehow, maybe similar to `TkAgendaTest`

**Comment by carlosmiranda** [comment]
@g4s8 I added `TkTeamTest`, please check

**Comment by carlosmiranda** [comment]
@g4s8 piing

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1382` is not assigned, can't get performer

**Pull request merged**
