### PR TITLE
better formatting of owned payments

### PR DESCRIPTION
**Pull request by krzyk**
Changed text joined with `;` to a simple list to make it look slightly less ugly.

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this pull request is too small, just 8 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@krzyk this PR can be related to this job: https://github.com/zerocracy/farm/issues/1193#issuecomment-398677712, do you want to complete here? I can assign you to #1193

**Comment by krzyk** [comment]
@g4s8 sure

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1423` is not assigned, can't get performer

**Pull request closed without merging**
