### PR TITLE
New kpi metrics

### PR DESCRIPTION
**Pull request by g4s8**
#2036 #2035 - new kpi metrics every day:
 - `active_projects` - amount of active projects (not on pause)
 - `active_users` - amount of users with reputation > 256
 - `visible_users` - amount of users with mentor and reputation > 0
 - `total_reputation` - total reputation of all visible users

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#2037](https://github.com/zerocracy/farm/issues/2037) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2037` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#2037](https://github.com/zerocracy/farm/issues/2037) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
