### PR TITLE
Fixed travis build

### PR DESCRIPTION
**Pull request by g4s8**
#716 - removed `set -e` from `.travis.yml`, it may cause strange behavior, see https://github.com/travis-ci/docs-travis-ci-com/issues/1672
Reproduced in #906

### CODE REVIEW

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review; in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@g4s8 this is not a proper fix in that case. A proper one would be to create `.travis/run.sh` script, which will do what we do now, and call it from `.travis.yml`

**Comment by g4s8** [comment]
@yegor256 fixed in 7edf53b

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Pull request merged**
