### PR TITLE
ZLD extra bonuses removed

### PR DESCRIPTION
**Pull request by g4s8**
#1820 - ZLD extra bonuses removed

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#1823](https://github.com/zerocracy/farm/issues/1823) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1823` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1823](https://github.com/zerocracy/farm/issues/1823) is now out of scope

**Pull request merged**
