### PR TITLE
#1919: On the board, separate project languages with commas *and spaces*

### LINKED ISSUE #1919: No spaces in the language list on the board
There are no spaces in the language list on the board. It looks like one long single word for an html rendering engine. In some cases it can breaks the layout.

image

### PR DESCRIPTION
**Pull request by vassilevsky**
This should fix #1919 and hopefully fix the board layout :3

### CODE REVIEW

**Comment by 0crat** [comment]
@vassilevsky[/z](https://www.0crat.com/u/vassilevsky) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@vassilevsky thanks!

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2064` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
