### PR TITLE
QA reviews

### PR DESCRIPTION
**Pull request by g4s8**
#646 - reviews todo

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#649](https://github.com/zerocracy/farm/issues/649) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#649](https://github.com/zerocracy/farm/issues/649) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/570705016). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by carlosmiranda** [comment]
@yegor256 good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), total is [+1635](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#649](https://github.com/zerocracy/farm/issues/649) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10909](https://www.0crat.com/u/yegor256)

**Pull request merged**
