### PR TITLE
Revert "Bump quartz from 2.2.1 to 2.3.2"

### PR DESCRIPTION
**Pull request by g4s8**
Reverts zerocracy/farm#2293

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor release, tag=`0.54.5`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@349556e6-fa72-4cfa-be64-c068e2ccb4e1, thread: pool-49-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/aibolit' repo was not found
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/aibolit' repo was not found
```

[0.54.5](https://github.com/zerocracy/farm): Issue: zerocracy/farm#2297, Action: `created`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2297` is not assigned, can't get performer

**Pull request merged**
