### PR TITLE
Fix VsBalance message

### PR DESCRIPTION
**Pull request by krzyk**
VsBalance message looks like this right now:
```
Has 15 jobs in 5 projects, 0.60% from current project
```

After the change it will be:
```
Has 15 jobs in 5 projects, 60% from current project
```

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@krzyk thanks

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@krzyk you have checkstyle error here:
> [INFO] Checkstyle: src/main/java/com/zerocracy/pm/staff/votes/VsBalance.java[101]: '100' is a magic number. (MagicNumberCheck)

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1614` is not assigned, can't get performer

**Pull request merged**
