### PR TITLE
(#2050) Exempt myself from §33 (http://www.zerocracy.com/policy.html#33)

### PR DESCRIPTION
**Pull request by andreoss**
- Work-around for #2050

### CODE REVIEW

**Comment by 0crat** [comment]
@andreoss[/z](https://www.0crat.com/u/andreoss) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Review by g4s8 — APPROVED** [review]
@andreoss thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2308` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
