### PR TITLE
For #1227: Added javadoc about ticket.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1227: Added javadoc about research work made in #1227.

### CODE REVIEW

**Comment by paulodamaso** [comment]
@g4s8 Some strange error happened in `Travis`: `The job exceeded the maximum time limit for jobs, and has been terminated.` pelase take a look.

**Comment by krzyk** [comment]
@paulodamaso you need to merge newest master, problem was fixed there

**Comment by paulodamaso** [comment]
@krzyk Which problem? There are neither conflics nor problems in the PR.

**Comment by krzyk** [comment]
@paulodamaso it was regarding your https://github.com/zerocracy/farm/pull/1523#issuecomment-409631376

**Comment by 0crat** [comment]
Job [#1523](https://github.com/zerocracy/farm/issues/1523) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1523#issuecomment-410007251))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1523](https://github.com/zerocracy/farm/issues/1523) is [in scope](http://www.zerocracy.com/policy.html#14) for 1days
  * The role is `REV`
  * The job is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk) for [24hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231523%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@krzyk ping

**Comment by paulodamaso** [comment]
@krzyk Don't worry, 0crat was a little upset today. About the `IllegalStateException` imports, we don't need to import `java.lang` classes (https://docs.oracle.com/javase/specs/jls/se10/html/jls-7.html):

> Code in a compilation unit automatically has access to all types declared in its package and also automatically imports all of the public types declared in the predefined package java.lang

I've made corrections for the other problems, please take a look. About the build failure, I've opened an issue (https://github.com/zerocracy/farm/issues/1535)

**Comment by krzyk** [comment]
@paulodamaso for the build failure you need to merge latest master, it is fixed there

**Comment by krzyk** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by krzyk** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1523#issuecomment-410476694))

@krzyk Job [#1523](https://github.com/zerocracy/farm/issues/1523) is not in the agenda of @krzyk[/z](https://www.0crat.com/u/krzyk), can't retrieve data and time of add

**Comment by krzyk** [comment]
@g4s8 `out` doesn't work here - can't move to QA

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1523#issuecomment-410476694))

@krzyk Job [#1523](https://github.com/zerocracy/farm/issues/1523) is not in the agenda of @krzyk[/z](https://www.0crat.com/u/krzyk), can't inspect

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1523#issuecomment-410476694))

@krzyk The job [#1523](https://github.com/zerocracy/farm/issues/1523) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1523#issuecomment-410626773))

@ypshenychka This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1523](https://github.com/zerocracy/farm/issues/1523) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 1days
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231523%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by krzyk** [comment]
@g4s8 I got points and shares, but not cash here

**Comment by g4s8** [comment]
@krzyk it's strange looks like this job was not estimated (no entry in `estimates.xml`), I'll add it to your debts manually.

**Comment by krzyk** [comment]
@g4s8 thanks, I see it now

**Pull request merged**
