### PR TITLE
#813 Re-enable RnkGithub, cache values to avoid Github API calls

### PR DESCRIPTION
**Pull request by carlosmiranda**
#813:

* `RnkGithub` is now using a global cache for referring Github issues, allowing us to avoid repeated API calls.
* Re-enabled `RnkGithub` in `elect_performer.groovy`.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#965](https://github.com/zerocracy/farm/issues/965) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#965](https://github.com/zerocracy/farm/issues/965) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1140231940); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by carlosmiranda** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@carlosmiranda it looks like that this solution will help ony for  github-bug labels ranks in election, maybe you can add `todo` to solve this problem overall?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@g4s8 I don't understand; `RnkGithubBug` really only deals with Github bug labels in election. What else is there?

**Comment by g4s8** [comment]
@carlosmiranda the issue #813 is not only about `RnkGithubBug`, also I can't implement new rank #575 because it will have same issues, so I think there should be more generic solution.

**Comment by carlosmiranda** [comment]
@g4s8 seems to me like a generalized solution would be too complicated, since we're getting different sets of data from Github here and in #575. I think each `RnkGithub*` class should just implement whatever caching mechanism required for it to get the data that it needs.

**Comment by carlosmiranda** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@carlosmiranda two thoughts here. First, let's use Cactoos caching with `StickyFunc`. Second, we should not rely on our assumptions, but instead check the quota available in GitHub. The cache should check the quota and hit GitHub only if it's acceptable at the moment. Otherwise, just ignore and say that the issue is "not a bug".

**Comment by carlosmiranda** [comment]
@yegor256 @g4s8 points addressed. Please check again.

**Comment by yegor256** [comment]
@rultor merge

**Comment by carlosmiranda** [comment]
@yegor256 can we try again? Unrelated error above.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#965](https://github.com/zerocracy/farm/issues/965) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@g4s8 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

Only one issue was found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by ypshenychka** [comment]
@g4s8 thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
