### PR TITLE
#435 Delete temp file on exit, if not marked for delete on close

### LINKED ISSUE #435: Too many temporary files after tests
Unit tests spawn a lot of temporary files which are not removed after tests. It may produce few Gb in a day. I think `File.deleteOnExit()` method for `FkItem` may help.

### PR DESCRIPTION
**Pull request by carlosmiranda**
#435: If delete flag on `FkItem` is false, mark the file for deletion at JVM exit instead.

### CODE REVIEW

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review; in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by carlosmiranda** [comment]
@yegor256 can we try this again?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
