### PR TITLE
Skip CR for small PR

### PR DESCRIPTION
**Pull request by g4s8**
#510 - check PR size in `Add job to WBS` claim for `REV` jobs. Tried to write bundle test, but found it impossible because of this bug: https://github.com/zerocracy/farm/issues/739
so I added a `@todo` for this test.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#740](https://github.com/zerocracy/farm/issues/740) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#740](https://github.com/zerocracy/farm/issues/740) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/652155650). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by g4s8** [comment]
@carlosmiranda sorry, forget to cleanup some spaces, should be fixed now

**Comment by g4s8** [comment]
@carlosmiranda fixed, please look again

**Comment by carlosmiranda** [comment]
@yegor256 good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by g4s8** [comment]
@yegor256 please, restart merge, it failed to push

чт, 8 марта 2018 г., 11:11 rultor.com <notifications@github.com>:

**Comment by yegor256** [comment]
@rultor mege

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#740](https://github.com/zerocracy/farm/issues/740) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@carlosmiranda According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by carlosmiranda** [comment]
@ypshenychka right, confirmed

**Comment by ypshenychka** [comment]
@carlosmiranda thank you

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Pull request merged**
