### PR TITLE
Disabled catalog test

### PR DESCRIPTION
**Pull request by g4s8**
#1990 - disabled catalog test

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1991` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1991](https://github.com/zerocracy/farm/issues/1991) is now out of scope

**Pull request merged**
