### PR TITLE
Using blanks metric for election

### PR DESCRIPTION
**Pull request by g4s8**
#1113 - using `blanks.xml` for election
#1507  - cleanup blanks, speed and other metrics every day

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#1995](https://github.com/zerocracy/farm/issues/1995) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1995` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1995](https://github.com/zerocracy/farm/issues/1995) is now out of scope

**Pull request merged**
