### PR TITLE
Skills

### PR DESCRIPTION
**Pull request by g4s8**
#492 - skills todo

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#513](https://github.com/zerocracy/farm/issues/513) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#513](https://github.com/zerocracy/farm/issues/513) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#513](https://github.com/zerocracy/farm/issues/513), please stop working

**Comment by 0crat** [comment]
This pull request [#513](https://github.com/zerocracy/farm/issues/513) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/431853408). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by yegor256** [comment]
@g4s8 this is a very small contribution for a single job. At least add a unit test, to validate that skills are updated.

**Comment by g4s8** [comment]
@yegor256 I have another PR in datum for same job: https://github.com/zerocracy/datum/pull/265
it contains 100 new lines of code, does it really small for one job?

**Comment by yegor256** [comment]
@g4s8 in such a case it's fine. It's my bad, I should not have stopped this PR. I should have raised this concern inside the issue, not in the PR. My bad.

**Comment by g4s8** [comment]
@yegor256 fixed typo, please restart merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), total is [+1305](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9809](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#513](https://github.com/zerocracy/farm/issues/513) is now out of scope

**Pull request merged**
