### PR TITLE
Project options

### PR DESCRIPTION
**Pull request by g4s8**
#1937 - added project options stakeholder, using `daysToCloseTask` option for `resign_on_delay`

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#2024](https://github.com/zerocracy/farm/issues/2024) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2024` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#2024](https://github.com/zerocracy/farm/issues/2024) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
