### PR TITLE
For #980: 0crat doesn't succeed paying via ethereum

### PR DESCRIPTION
**Pull request by paulodamaso**
Result from #980:
We need to drop Etherium support from Zerocracy

Remove ETH support mentioned in Policy (https://www.zerocracy.com/policy.html#20)
Remove ETH wallets support informing that ETH cannot be used when user tries to use it.

### CODE REVIEW

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this pull request is too small, just 3 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1303` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Pull request merged**
