### PR TITLE
Serve resized profile photos on gang and other pages

### PR DESCRIPTION
**Pull request by terales**
After a recent update on socatar.com it's possible now to request the required image size.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#519](https://github.com/zerocracy/farm/issues/519) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#519](https://github.com/zerocracy/farm/issues/519) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by yegor256** [comment]
@terales this will make them look ugly on Retina screens. At least 2x is required.

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/519#issuecomment-362912374))

@yegor256 This pull request [#519](https://github.com/zerocracy/farm/issues/519) is assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9255](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@terales also, check `profile.xsl`, we use socatar there too

**Comment by terales** [comment]
@yegor256 Done. Thanks for feedback

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9265](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9280](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#519](https://github.com/zerocracy/farm/issues/519) is now out of scope

**Pull request merged**
