### PR TITLE
For #770: Do not add small pull requests to WBS.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #770: Do not add small pull requests to WBS:
- Corrected `add_job_to_wbs.groovy`
- Added tests

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1693](https://github.com/zerocracy/farm/issues/1693) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1693` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1693](https://github.com/zerocracy/farm/issues/1693) is now out of scope

**Pull request merged**
