### PR TITLE
fix typo fails should be files

### PR DESCRIPTION
**Pull request by avidrucker**

### CODE REVIEW

**Comment by 0crat** [comment]
@avidrucker[/z](https://www.0crat.com/u/avidrucker) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by avidrucker** [comment]
@yegor256 What do you recommend I do differently in the future for small typo fixes? Ignore them?

**Comment by yegor256** [comment]
@avidrucker thanks! typo fixes are always welcome! please, send them over.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2341` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
