### PR TITLE
Impediments fix

### LINKED ISSUE #2081: Wait command should not be accepted from dev who is not assigned to the issue
Currently if a project dev asks 0crat to wait on an issue that command is accepted even when the dev is no longer the one assigned to the issue. Let's make 0crat refuse these requests unless they come from the assigned dev or from the ARC or the PO.

image

### PR DESCRIPTION
**Pull request by g4s8**
#2081 - allow registering impediments only to job performers and users with `ARC` or `PO` role

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#2083](https://github.com/zerocracy/farm/issues/2083) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2083` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#2083](https://github.com/zerocracy/farm/issues/2083) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
