### PR TITLE
#229 assign_role fails if user is not on Github

### PR DESCRIPTION
**Pull request by amihaiemil**
Pr for #229 

The code is rather ugly and it cannot easily be tested because MkUser does not behave the same as RtUser -- MkUser.json() simply returns ``{login: username}`` for any login input. In order to properly test this scenario, we would need another mock implementation of User, decorate the test Github instance somehow (its Users, to be more precise, they should return another version of MkUser). 

Furthermore, the user ``Github`` instance is wraped inside ``ExtGithub`` scalar and cannot be changed at all -- that class should be refactored.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#719](https://github.com/zerocracy/farm/issues/719) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#719](https://github.com/zerocracy/farm/issues/719) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/631544962). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@yegor256 @carlosmiranda don't merge it yet, I noticed the test for it is silently swallowing an exception (MkUser does not have the ``followersCount`` attribute, so it throws IllegalStateException) -- this means that a possible exception will probably be swallowed at runtime as well. I will remove that count display today :)

**Comment by amihaiemil** [comment]
@yegor256 I removed the ``followersCount`` and opened an Issue regarding that exception swallowing. This can be merge now, imo.

**Comment by yegor256** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@yegor256 PR is merged, can you close this?

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@carlosmiranda According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by carlosmiranda** [comment]
@ypshenychka confirmed

**Comment by ypshenychka** [comment]
@carlosmiranda thank you

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/zerocracy/farm/issues/719#issuecomment-371050925))

@ypshenychka You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/zerocracy/farm/issues/719#issuecomment-371050925))

@ypshenychka I didn't understand what is "acceptable"

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/zerocracy/farm/issues/719#issuecomment-371189812))

@ypshenychka Thanks, but `QA` review is not required in this job

**Comment by yegor256** [comment]
@0crat out

**Comment by yegor256** [comment]
@0crat pay 15min @carlosmiranda

**Comment by yegor256** [comment]
@0crat pay 8min @ypshenychka

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/719#issuecomment-371403242))

@yegor256 @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#719](https://github.com/zerocracy/farm/issues/719), since the job is not in scope anymore

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/719#issuecomment-371403242))

@yegor256 The job [#719](https://github.com/zerocracy/farm/issues/719) is now out of scope

**Comment by 0crat** [comment]
Direct payment from @yegor256[/z](https://www.0crat.com/u/yegor256): +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Direct payment to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) in #719, which is discouraged, see [§49](http://www.zerocracy.com/policy.html#49): -60 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Direct payment from @yegor256[/z](https://www.0crat.com/u/yegor256): +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Direct payment to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) in #719, which is discouraged, see [§49](http://www.zerocracy.com/policy.html#49): -60 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Pull request merged**
