### PR TITLE
Duplicated bans

### PR DESCRIPTION
**Pull request by g4s8**
#465 - added check in `Bans`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#638](https://github.com/zerocracy/farm/issues/638) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#638](https://github.com/zerocracy/farm/issues/638) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/550963404). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by yegor256** [comment]
@g4s8 I don't like it. We should prevent this from happening, instead of deleting the old data silently. Let's do something like

```
if (!bans.exists(...)) {
  bans.add(...);
}
```

**Comment by g4s8** [comment]
@yegor256 please see new changes

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), total is [+1605](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#638](https://github.com/zerocracy/farm/issues/638) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10894](https://www.0crat.com/u/yegor256)

**Pull request merged**
