### PR TITLE
#1071 Implement VbBot.sendMessage

### PR DESCRIPTION
**Pull request by carlosmiranda**
#1071: Implemented `VbBot.sendMessage`. Added unit test; added puzzle to allow notification via Viber.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1436](https://github.com/zerocracy/farm/issues/1436) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1436](https://github.com/zerocracy/farm/issues/1436) is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1980811094); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by krzyk** [comment]
@carlosmiranda looks good

**Comment by krzyk** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by carlosmiranda** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1436](https://github.com/zerocracy/farm/issues/1436) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by ypshenychka** [comment]
@krzyk According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

Only one issue was found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by krzyk** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@krzyk thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@carlosmiranda the puzzle [#1480](https://github.com/zerocracy/farm/issues/1480) is still not solved.

**Comment by 0pdd** [comment]
@carlosmiranda the only puzzle [#1480](https://github.com/zerocracy/farm/issues/1480) is solved here.

**Comment by 0pdd** [comment]
@carlosmiranda the puzzle [#1532](https://github.com/zerocracy/farm/issues/1532) is still not solved; solved: [#1480](https://github.com/zerocracy/farm/issues/1480).

**Comment by 0pdd** [comment]
@carlosmiranda all 2 puzzles are solved here: [#1480](https://github.com/zerocracy/farm/issues/1480), [#1532](https://github.com/zerocracy/farm/issues/1532).

**Pull request merged**
