### PR TITLE
#1279 ProjectsRoles to check user roles across all projects

### PR DESCRIPTION
**Pull request by carlosmiranda**
#1279: Moved common role checking code in `RqUser` and `RqLogin` to `ProjectsRoles`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1757](https://github.com/zerocracy/farm/issues/1757) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by carlosmiranda** [comment]
@g4s8 merged with master, let's try again. Build seems to be ok locally.

**Comment by g4s8** [comment]
@rultor merge

**Pull request merged**
