### PR TITLE
Check recharge need before recharging

### PR DESCRIPTION
**Pull request by g4s8**
#1672 - add check `recharge.required` before recharging. Added unique signature source for all recharge claims in project, but keep claims flow.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1676](https://github.com/zerocracy/farm/issues/1676) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1676` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1676](https://github.com/zerocracy/farm/issues/1676) is now out of scope

**Pull request merged**
