### PR TITLE
Unique project idsfor bundles

### PR DESCRIPTION
**Pull request by g4s8**
#1238 - Fail bundle test if `pid` duplicates found, renamed all bundles to have unique pids

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#1949](https://github.com/zerocracy/farm/issues/1949) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1949` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1949](https://github.com/zerocracy/farm/issues/1949) is now out of scope

**Pull request merged**
