### PR TITLE
#1280 periodically add reviews to QA agenda

### PR DESCRIPTION
**Pull request by krzyk**
#1280 
* QA agenda is periodically extended by reviews where he/she is an inspector

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1735](https://github.com/zerocracy/farm/issues/1735) is now in scope, role is `REV`

**Comment by krzyk** [comment]
@g4s8 Looks like 0crat assigned this to me (at least it appeared in my agenda)

**Comment by 0crat** [comment]
This pull request [#1735](https://github.com/zerocracy/farm/issues/1735) is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2712051808); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1735#issuecomment-425625386))

@g4s8 The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#1735](https://github.com/zerocracy/farm/issues/1735), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#1735](https://github.com/zerocracy/farm/issues/1735) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2720812917); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by krzyk** [comment]
@paulodamaso ping

**Comment by krzyk** [comment]
@paulodamaso updated

**Comment by paulodamaso** [comment]
@krzyk there are some test failures please take a look

**Comment by krzyk** [comment]
@paulodamaso this tests fails sometimes (changing user rate), so it is not related to this change

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1735](https://github.com/zerocracy/farm/issues/1735) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by ypshenychka** [comment]
@paulodamaso According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

Only minor issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by paulodamaso** [comment]
@ypshenychka I don't see them as minor problems: all of them improves code readability, thus improving coding quality

**Comment by ypshenychka** [comment]
@paulodamaso I can't agree with you. So let's better ask @g4s8. Please advise whether these three found issues are major or not.

**Comment by ypshenychka** [comment]
@g4s8 ping

**Comment by ypshenychka** [comment]
@g4s8 Please let us know what do you think regarding this [comment](https://github.com/zerocracy/farm/pull/1735#issuecomment-426606830).

**Comment by g4s8** [comment]
@ypshenychka comments by @paulodamaso really improves code readability, but I'd not call them "major bugs".

**Comment by ypshenychka** [comment]
@g4s8 thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
