### PR TITLE
Notify about PO reports

### PR DESCRIPTION
**Pull request by g4s8**
#1784
 - added 2weeks pings
 - added stakeholder to notify ARCs about PO reports
 - minor fixes related to `Par` responses

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1785](https://github.com/zerocracy/farm/issues/1785) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1785` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1785](https://github.com/zerocracy/farm/issues/1785) is now out of scope

**Pull request merged**
