### PR TITLE
Read-write resource access

### PR DESCRIPTION
**Pull request by g4s8**
#2240 - changed `Item` interface: added `read` and `update` methods, updated `SyncItem` implementation using `ReadWriteLock`s, changed all other code to support new `Item` interface.

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2247` is not assigned, can't get performer

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
