### PR TITLE
Twitter API wrapper

### PR DESCRIPTION
**Pull request by g4s8**
#495 - wrap twitter API use

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#669](https://github.com/zerocracy/farm/issues/669) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#669](https://github.com/zerocracy/farm/issues/669) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/591358153). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by carlosmiranda** [comment]
@yegor256 looks good to merge here

**Comment by yegor256** [comment]
@g4s8 let's use it in `RbTweet` too

**Comment by g4s8** [comment]
@yegor256 done 369dde8

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#669](https://github.com/zerocracy/farm/issues/669) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Pull request merged**
