### PR TITLE
correcting claim type for set title stk

### PR DESCRIPTION
**Pull request by krzyk**
'set title' stakeholder was attached to `Start order` which happens before the agenda is updated, so it couldn't update the tile in agenda.
Updated it to attach to `Agenda was updated`.

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this pull request is too small, just 7 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@rultor merge

**Comment by krzyk** [comment]
@g4s8 could you try to merge again, I did merge master (although it shouldn't be needed, changes were in different file).

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1323` is not assigned, can't get performer

**Pull request merged**
