### PR TITLE
Pay ARC bonus on remove from WBS

### PR DESCRIPTION
**Pull request by g4s8**
#2020 - pay ARC bonus on remove from WBS

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#2022](https://github.com/zerocracy/farm/issues/2022) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2022` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#2022](https://github.com/zerocracy/farm/issues/2022) is now out of scope

**Pull request merged**
