### PR TITLE
Test performance

### PR DESCRIPTION
**Pull request by g4s8**
#1347 - improved performance of bundle tests

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1698](https://github.com/zerocracy/farm/issues/1698) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Pull request merged**
