### PR TITLE
Added qa commands

### PR DESCRIPTION
**Pull request by g4s8**
#408 - added qa commands

### CODE REVIEW

**Comment by g4s8** [comment]
moved to #460 (missed fork)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8190](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#414](https://github.com/zerocracy/farm/issues/414) is now out of scope

**Comment by 0crat** [comment]
Job [#414](https://github.com/zerocracy/farm/issues/414) was not in scope

**Pull request closed without merging**
