### PR TITLE
 #1778 - improve table layout in board page

### PR DESCRIPTION
**Pull request by filfreire**
@g4s8 and @yegor256 here is a solution to #1778, at least until we can perfect tables in tacit (or create a proper CSS lib to handle complex cases for tables.

Included in this change:
- rawgit cdn will become deprecated, replaced it (see https://rawgit.com/ )
- pointing to latest version of tacit (which includes table layout change, https://github.com/yegor256/tacit/releases/tag/1.4.1 )

Here's how `/board` page should look from now on:

**Desktop:**
screen shot 2019-02-28 at 23 07 56

**Mobile:**
screen shot 2019-02-28 at 23 08 15

**Note:** I'm not sure this is the right file to change to update `0crat.com`, point me out in the right direction if it's a different file.

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@filfreire thanks, will try it

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor release, tag=`0.43.2`

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1914` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
