### PR TITLE
#1168 disabling firefox transformation

### PR DESCRIPTION
**Pull request by krzyk**
#1168 
Disabling Firefox Saxon transformations - might help with OOM

### CODE REVIEW

**Comment by g4s8** [comment]
@krzyk looks like you have some error in build:
>[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.17.1:check (jcabi-check) on project farm: Failure: There are 1 violations -> [Help 1]

**Comment by krzyk** [comment]
@g4s8 sorry, merge issue, now it will work

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@42035a22-4829-4612-bc0a-71dc95f86d80, thread: AsyncFlush-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "blanks/krzyk.xml" in "PMO" in 2min: c206822b11f7/4min/0/4/true/false by QuartzScheduler_Worker-1
```

[0.22.23](https://github.com/zerocracy/farm): CID: [1720803035](https://www.0crat.com/C3NDPUA8L/1720803035), Type: "Close job", Author: "g4s8"

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1198` is not assigned, can't get performer

**Pull request merged**
