### PR TITLE
Sort reputation as number

### PR DESCRIPTION
**Pull request by mazdack**
https://github.com/zerocracy/farm/issues/502 - Sort reputation as number

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#504](https://github.com/zerocracy/farm/issues/504) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#504](https://github.com/zerocracy/farm/issues/504) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/504#issuecomment-362608430))

@yegor256 The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#504](https://github.com/zerocracy/farm/issues/504), please stop working

**Comment by yegor256** [comment]
@mazdack thanks!

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#504` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#504](https://github.com/zerocracy/farm/issues/504) is now out of scope

**Pull request merged**
