### PR TITLE
Cleanup comments

### PR DESCRIPTION
**Pull request by g4s8**
#376 - cleanup comments

@yegor256 I'm not sure how to write tests for DynamoDB, could you please advice me?

### CODE REVIEW

**Comment by g4s8** [comment]
@yegor256 same as here: https://github.com/zerocracy/farm/pull/440#issuecomment-360088418

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8060](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8075](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#379](https://github.com/zerocracy/farm/issues/379) is now out of scope

**Comment by 0crat** [comment]
Job [#379](https://github.com/zerocracy/farm/issues/379) was not in scope

**Pull request closed without merging**
